config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # resources :movies

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  # validates :image_url, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.new(bookmark_params)
    @bookmark.list_id = @list.id
    # raise
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def show
    @bookmarks = @list.bookmarks

  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path
  end

  def destroy
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>youpi new bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all.map { |m| [m.title, m.id] }%>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>youpi modify lists</h1>

app/views/lists/index.html.erb
<img src="https://media.istockphoto.com/id/1007557230/fr/photo/projecteur-de-film-sur-fond-fonc%C3%A9.jpg?s=1024x1024&w=is&k=20&c=WD279MD9d6CP7oQEW394I_EnovQ5kak7OKir6WW4Z2Q=" alt="">
<h1>youpi all lists</h1>


<ul>
  <%@lists.each do |list|%>
    <li>
      <%=link_to list.name, list_path(list)%>
      <%if (list.image_url != nil)%>
        <img src=<%=list.image_url%> alt="pas d'image">
      <%end%>
    </li>
  <%end%>
</ul>

<p><%=link_to "Create new list", new_list_path%>% </p>

app/views/lists/new.html.erb
<h1>youpi new list</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%=@list.name%></h1>
<img src=<%=@list.image_url%> alt="">

<%@bookmarks.each do |bookmark|%>
  <li><%=Movie.find(bookmark.movie_id).title%> - <%=bookmark.comment%>
    <img src=<%=Movie.find(bookmark.movie_id).poster_url%> alt="">
  </li>
<%end%>

<p><%=link_to "create new bookmark", new_list_bookmark_path(@list)%></p>
<p><%=link_to "back", lists_path%></p>

app/views/movies/index.html.erb
<h1>youpimovie</h1>

<%= simple_form_for(@movies) do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>